# Generated by Django 4.2.2 on 2023-06-25 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_image_folder_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="folder_name",
        ),
        migrations.RemoveField(
            model_name="image",
            name="name",
        ),
    ]
