# Generated by Django 4.2.3 on 2023-07-06 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FourthModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field_four", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ThirdModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field_three", models.CharField(max_length=100)),
                (
                    "fourth_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nested.fourthmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SecondModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field_two", models.CharField(max_length=100)),
                (
                    "third_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nested.thirdmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FirstModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text_field_one", models.CharField(max_length=100)),
                (
                    "second_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nested.secondmodel",
                    ),
                ),
            ],
        ),
    ]
