# Generated by Django 4.2.2 on 2023-06-29 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_remove_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
