# Generated by Django 4.2.2 on 2023-06-29 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
